@baseUrl = http://localhost:3333



GET {{baseUrl}}/health
###
GET {{baseUrl}}/rooms
###
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name": "sala de teste",
    "description": "Essa é uma sala de teste"
}